---
- name: Install Docker Pre-Req
  apt:
    update_cache: yes
    name: "{{ item }}"
  loop: "{{ docker_req_pack }}"
    
- name: add gpg key
  shell: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -

- name: set repo
  shell: |
          sudo add-apt-repository \
          "deb [arch=amd64] https://download.docker.com/linux/ubuntu \
          $(lsb_release -cs) \
          stable"

#- name: curl docker
#  shell: curl -fsSL https://get.docker.com | bash

#- name: Install docker
#  apt:
#    name: "{{ item }}"
#    state: present
#  loop: "{{ docker_pack}}"

- name: Install Docker
  shell: apt-get install {{ item }} -y --allow-downgrades
  loop: "{{ docker_pack }}"

- name: add group docker
  become: yes
  shell: usermod -aG docker ubuntu

- name: Docker start
  systemd:
    name: docker
    state: started
    enabled: yes